spring:
  application:
    name: payment
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
  redis:
    host: localhost
    port: 6379

server:
  port: 8081

logging:
  level:
    root: DEBUG

token-issuance:
  service:
    url: http://localhost:8080

authorization:
  service:
    url: http://localhost:8082
